### ISSUE TITLE
NPE  at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)

### ISSUE THREAD

**Issue by dfurmans** [FlakM/InMemoryLdap#4]
Want to use the LDAP in Memory within the Play Framework
I end up with the error 
```
[info] AuthServiceImplementationLdapDBIOSpec:
[info] - AuthServiceImplementationLdapDBIOSpec *** FAILED ***
[info]   java.lang.NullPointerException:
[info]   at com.github.flakm.InMemoryLdapServer$.$anonfun$startInternal$1(InMemoryLdapServer.scala:65)
[info]   at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
[info]   at com.github.flakm.InMemoryLdapServer$.startInternal(InMemoryLdapServer.scala:64)
[info]   at com.github.flakm.InMemoryLdapServer$.withRunningLdapConfig(InMemoryLdapServer.scala:96)
[info]   at com.github.flakm.InMemoryLdapServer$.withRunningLdap(InMemoryLdapServer.scala:91)
[info]   at module.session.service.AuthServiceImplementationLdapDBIOSpec.$anonfun$new$1(AuthServiceImplementationLdapDBIOSpec.scala:24)
```

**Comment by FlakM** [comment]
Hello, could you please provide some reproducer?

czw., 6 maj 2021, 15:57 użytkownik Dawid Furman ***@***.***>
napisał:

**Comment by dfurmans** [comment]
Maybe I should create my own configuration or provide an configuration file - but should works as well without define it - out to the box - is it correct? 

The class is run-up within the `sbt testOnly`
```
package module.session.service

import org.scalatestplus.play._
import org.scalatest.words._
import org.scalatestplus.play.guice.GuiceOneAppPerSuite
import play.api.Configuration
import web.module.user.repository.implementation.user.UserRepositoryImplementationDBIO
import com.github.flakm.InMemoryLdapServer._
import com.unboundid.ldap.listener.InMemoryListenerConfig

import java.net.InetAddress
import javax.naming.ldap.LdapContext

class AuthServiceImplementationLdapDBIOSpec extends PlaySpec with GuiceOneAppPerSuite{

  // in memory LDAP connection
  // configure ldap
  val conf     = app.injector.instanceOf[Configuration]
  val userRepo = app.injector.instanceOf(classOf[UserRepositoryImplementationDBIO])

  // create controller
  import web.module.session.service.implementation.auth._
  val aAuthService = new AuthServiceImplementationLdapDBIO()(conf, userRepo)

  "AuthServiceImplementationLdapDBIOSpec" in {
    withRunningLdap { implicit ctx =>
        println(ctx)
       //todo 
      }
  }
}
```

**Comment by FlakM** [comment]
You should provide some files in test resources for defaults to work. 
Directory `src/test/resources/ldap` should contain your ldap structure scripts. `src/test/resources/ssl`  should contain truststore, client and server stores with valid certificates to test ldaps connection. 

Investigate examples in repository:

```
$ tree src/test/resources/
src/test/resources/
├── application.conf
├── create_keys.sh
├── ldap
│   ├── add_lily.ldif
│   └── test-data.ldif
├── logback-test.xml
└── ssl
    ├── client.jks
    ├── server.jks
    └── trust.jks
```


The error handling here is terrible, so if you don't mind i will it leave it open untill i get some free time to fix it ;)

**Comment by dfurmans** [comment]
oki doki! 
Could you please add me as a collaborator to the project. Would be great to bump a `unboundid-ldapsdk` as well. 
I really enjoy the small code base here and would like to put a little my hand into it :sunny:

**Comment by FlakM** [comment]
I'd be happy to take PR, please follow https://guides.github.com/activities/forking/ to submit a PR. Also if you want you can fix nasy NPE at the same time ;)

**Comment by FlakM** [comment]
Closed by https://github.com/FlakM/InMemoryLdap/pull/5
